minimumReleaseAge: 20160
overrides:
  undici@<6.23.0: '>=6.23.0'
  undici@<6.24.0: '>=6.24.0'
  ws@>=8.0.0 <8.20.1: '>=8.20.1'

patchedDependencies:
  '@projectdysnomia/dysnomia': patches/@projectdysnomia__dysnomia.patch
